config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
  	root to: "devise/sessions#new"
	end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "users/registrations" } 
  else
    devise_for :users
  end

  resources :users do
  	resource :profile
	end

	resources :customers
	resources :customers_statuses
	resources :vendors
	resources :vendors_statuses
	resources :vendors_types

  get 'home', to: 'pages#home'
  get 'vendors', to: 'pages#vendors'
  get 'reports', to: 'pages#reports'
  get 'admin', to: 'admin#home'
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates_presence_of :company_name, :phone_number, :email_address
	belongs_to :customers_status
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customers_statuses_id, :company_name, :customer_notes, :address_line_one, :address_line_two, :city, :zip_code, :phone_number, :email_address)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name %>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :customer_status %>
    <%= f.collection_select :customers_statuses_id, CustomersStatus.all, :id, :title, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email_address %>
    <%= f.text_field :email_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_one %>
    <%= f.text_field :address_line_one, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_two %>
    <%= f.text_field :address_line_two, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :customer_notes %>
    <%= f.text_area :customer_notes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/customers/_view-customers.html.erb
<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td class="customer-name"><%= link_to customer.company_name, customer, remote: true %></td>
        <td class="customer-name"><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td class="customer-name"><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, class: 'btn btn-success' %>

app/views/customers/_view_customers.html.erb
<table>
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.company_name, customer %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.email_address %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/edit.html.erb
<div class="block-callout container-fluid">
	<h2>Customer Information Management</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Manage your customers information here.</h6>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Edit Customer</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form', customer: @customer %>
			  </div>
			</div>
			<%= link_to 'Back', customers_path, class: 'btn btn-danger' %>
		</div>
	</div>
</div>

app/views/customers/index.html.erb
<div class="block-callout container-fluid">
	<h2>Customer List</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Manage and view important information about all Nicholson Plumbing customers.</h6>
</div>
<div class="col-md-12">
	<div class="panel panel-default">
	  <div class="panel-body customer-panel">
	  	<%= render 'view_customers' %>
	  </div>
	</div>
</div>

app/views/customers/new.html.erb
<div class="block-callout container-fluid">
	<h2>Customer Creation</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Add new customers to the database through this form.</h6>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Create New Customer</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form', customer: @customer %>
			  </div>
			</div>
			<%= link_to 'Back', customers_path, class: 'btn btn-danger' %>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<div class="block-callout container-fluid">
	<div class="row">
	  <div class="col-md-10">
	 		<h2>Customer Detailed Information</h2>
	  </div>
	  <div class="col-md-2">
	  	<%= link_to 'Back', customers_path, class: 'btn btn-danger escape-button' %>
		</div>
	</div>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">View a clients detailed information here.</h6>
</div>
<div class="container-fluid">
	<div class="row">
		<!-- Customer Projects Panel -->
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Customer Information</h3>
        </div>
        <div class="panel-body">
          <div class="col-md-6">
				  	<p class="company-info-header"><%= @customer.company_name %></p>
				  	<p>
				  		<%= @customer.address_line_one %><br>
							<%= @customer.address_line_two %><br>
							<%= @customer.city + ', Insert State' %><br>
							<%= @customer.zip_code %>
						</p>
				  </div>
				  <div class="col-md-4 col-md-offset-2">
				  	<p class="company-info-header">Contact Info</p>
				  	<p>
				  		<%= @customer.phone_number %><br>
							<%= @customer.email_address %>
						</p>
				  </div>
        </div>
      </div>
    </div>
		<!-- Customer Projects Panel -->
    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Projects</h3>
        </div>
        <div class="panel-body">
          <table>
					  <thead>
					    <tr>
					      <th>Project Name</th>
					      <th>Start Date</th>
					      <th>End Date</th>
					      <th>Type</th>
					      <th>Total Cost</th>
					    </tr>
					  </thead>
					  <tbody>
				      <tr>
				        <td>Arrowmont Constructors</td>
				        <td>01/01/2016</td>
				        <td>02/01/2016</td>
				        <td>Commercial</td>
				        <td>$50,000</td>
				      </tr>
				      <tr>
				        <td>US Builders</td>
				        <td>01/01/2016</td>
				        <td>02/01/2016</td>
				        <td>Commercial</td>
				        <td>$75,000</td>
				      </tr>
					  </tbody>
					</table>
        </div>
      </div>
    </div>
  </div>
  <!-- Second Row -->
  <div class="row">
  	<!-- Customer Quick Reports Panel -->
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Quick Reports</h3>
        </div>
        <div class="panel-body">
        	<ul class="reports-list">
        		<li>Report One</li>
        		<li>Report Two</li>
        		<li>Report Three</li>
        		<li>Report Four</li>
        		<li>Report Five</li>
          </ul>
        </div>
      </div>
    </div>
		<!-- Customer Invoices Panel -->
    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Invoices</h3>
        </div>
        <div class="panel-body">
          <table>
					  <thead>
					    <tr>
					    	<th>Invoice #</th>
					      <th>Project Name</th>
					      <th>Billed Date</th>
					      <th>Due Date</th>
					      <th>Type</th>
					      <th>Total Due</th>
					    </tr>
					  </thead>
					  <tbody>
				      <tr>
				      	<td>#001</td>
				        <td>Arrowmont Constructors</td>
				        <td>01/01/2016</td>
				        <td>02/01/2016</td>
				        <td>Commercial</td>
				        <td>$35,000</td>
				      </tr>
				      <tr>
				      	<td>#002</td>
				        <td>Arrowmont Constructors</td>
				        <td>02/01/2016</td>
				        <td>03/01/2016</td>
				        <td>Commercial</td>
				        <td>$15,000</td>
				      </tr>
				      <tr>
				      	<td>#003</td>
				        <td>US Builders</td>
				        <td>01/01/2016</td>
				        <td>02/01/2016</td>
				        <td>Commercial</td>
				        <td>$50,000</td>
				      </tr>
				      <tr>
				      	<td>#004</td>
				        <td>US Builders</td>
				        <td>01/01/2016</td>
				        <td>02/01/2016</td>
				        <td>Commercial</td>
				        <td>$25,000</td>
				      </tr>
					  </tbody>
					</table>
        </div>
      </div>
    </div>
  </div>
</div>