config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
  	root to: "devise/sessions#new"
	end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "users/registrations" } 
  else
    devise_for :users
  end

  resources :users do
  	resource :profile
	end

	resources :customers
	resources :customers_statuses
	resources :vendors
	resources :vendors_statuses
	resources :vendors_types

  get 'home', to: 'pages#home'
  get 'vendors', to: 'pages#vendors'
  get 'reports', to: 'pages#reports'
  get 'admin', to: 'admin#home'
end

app/models/vendor.rb
class Vendor < ApplicationRecord
	validates_presence_of :company_name, :phone_number, :email_address
	belongs_to :vendors_status
	belongs_to :vendors_type
end

app/models/vendors_type.rb
class VendorsType < ApplicationRecord
	validates_presence_of :title, :description
	has_many :vendor
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @vendors = Vendor.all
  end

  def show
  end

  def new
    @vendor = Vendor.new
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendors_path, notice: 'Vendor was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendors_path, notice: 'Vendor was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendors_statuses_id, :vendors_types_id, :company_name, :vendor_notes, :address_line_one, :address_line_two, :city, :zip_code, :phone_number, :email_address)
    end
end

app/views/vendors/_form.html.erb
<%= form_for(vendor) do |f| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name %>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>

    <div class="form-group">
    <%= f.label :vendor_type %>
    <%= f.collection_select :vendors_types_id, VendorsType.all, :id, :title, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :vendor_status %>
    <%= f.collection_select :vendors_statuses_id, VendorsStatus.all, :id, :title, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email_address %>
    <%= f.text_field :email_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_one %>
    <%= f.text_field :address_line_one, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_two %>
    <%= f.text_field :address_line_two, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :vendor_notes %>
    <%= f.text_area :vendor_notes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vendors/index.html.erb
<div class="block-callout container-fluid">
	<h2>Vendor List</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Manage and view important information about all Nicholson Plumbing vendors.</h6>
</div>
<div class="col-md-12">
	<div class="panel panel-default">
	  <div class="panel-body customer-panel">
	  	<table>
			  <thead>
			    <tr>
			      <th>Vendor Name</th>
			      <th>Phone Number</th>
			      <th>Email</th>
			      <th>Edit</th>
			      <th>Delete</th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @vendors.each do |vendor| %>
			      <tr>
			        <td><%= link_to vendor.company_name, vendor %></td>
			        <td><%= vendor.phone_number %></td>
			        <td><%= vendor.email_address %></td>
			        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
			        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
	  </div>
	</div>
</div>

app/views/vendors/new.html.erb
<div class="block-callout container-fluid">
	<h2>Vendor Creation</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Add new vendors to the database through this form.</h6>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Create New Vendor</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form', vendor: @vendor %>
			  </div>
			</div>
			<%= link_to 'Back', vendors_path, class: 'btn btn-danger' %>
		</div>
	</div>
</div>