config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
  	root to: "devise/sessions#new"
	end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "users/registrations" } 
  else
    devise_for :users
  end

  resources :users do
  	resource :profile
	end

	resources :customers
	resources :customers_statuses
	resources :vendors
	resources :vendors_statuses
	resources :vendors_types

  get 'home', to: 'pages#home'
  get 'vendors', to: 'pages#vendors'
  get 'reports', to: 'pages#reports'
  get 'admin', to: 'admin#home'
end

app/controllers/vendors_statuses_controller.rb
class VendorsStatusesController < ApplicationController
	before_action :set_vendors_status, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@vendors_statuses = VendorsStatus.all
	end

	def show
	end

	def new
		@vendors_status = VendorsStatus.new
	end

	def edit
	end

	def create
		@vendors_status = VendorsStatus.new(vendors_status_params)

		respond_to do |format|
			if @vendors_status.save
				format.html { redirect_to vendors_statuses_path, notice: 'Vendor status was successfully created.' }
			else
				format.html { render :new }
			end
		end
	end

	def update
		respond_to do |format|
			if @vendors_status.update(vendors_status_params)
				format.html { redirect_to vendors_statuses_path, notice: 'Vendor status was successfully updated.' }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@vendors_status.destroy
		respond_to do |format|
			format.html { redirect_to vendors_statuses_path, notice: 'Vendor status was successfully updated.' }
		end
	end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vendors_status
    @vendors_status = VendorsStatus.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vendors_status_params
    params.require(:vendors_status).permit(:title, :description)
  end

end

app/views/vendors_statuses/_form.html.erb
<%= form_for(vendors_status) do |f| %>
  <% if vendors_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendors_status.errors.count, "error") %> prohibited this vendors status from being saved:</h2>

      <ul>
      <% vendors_status.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vendors_statuses/index.html.erb
<div class="block-callout container-fluid">
	<h2>Vendor Statuses Management</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Manage vendor statuses for use in the vendor management screen.</h6>
</div>
<div class="col-md-12">
	<div class="panel panel-default">
	  <div class="panel-body customer-panel">
	  	<table>
			  <thead>
			    <tr>
			      <th>Title</th>
			      <th>Description</th>
			      <th>Edit</th>
			      <th>Delete</th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @vendors_statuses.each do |vendors_status| %>
			      <tr>
			        <td><%= vendors_status.title %></td>
			        <td><%= vendors_status.description %></td>
			        <td><%= link_to 'Edit', edit_vendors_status_path(vendors_status) %></td>
			        <td><%= link_to 'Destroy', vendors_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
	  </div>
	</div>
</div>

app/views/vendors_statuses/new.html.erb
<div class="block-callout container-fluid">
	<h2>Vendor Status Creation</h2>
	<div class="horizontal-line">&nbsp;</div>
	<h6 class="sub-block-callout">Add new vendor statuses to the database here.</h6>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Create New Vendor Status</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form', vendors_status: @vendors_status %>
			  </div>
			</div>
			<%= link_to 'Back', vendors_statuses_path, class: 'btn btn-danger' %>
		</div>
	</div>
</div>