config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
  	root to: "devise/sessions#new"
	end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "users/registrations" } 
  else
    devise_for :users
  end

  resources :users do
  	resource :profile
	end

	resources :customers
	resources :customers_statuses
	resources :vendors
	resources :vendors_statuses
	resources :vendors_types

  get 'home', to: 'pages#home'
  get 'vendors', to: 'pages#vendors'
  get 'reports', to: 'pages#reports'
  get 'admin', to: 'admin#home'
end

app/views/layouts/navigation/_login_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to home_path, class: "navbar-brand" do %>
			  <i class="fa fa-gears"></i>
			  D.U.K.E.
			<% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
    	<div class="nav navbar-nav navbar-right">
			  <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
			</div>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/navigation/_side_navigation.html.erb
<nav class="navbar navbar-inverse sidebar" role="navigation">
  <div class="container-fluid">
  	<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to home_path, :class => 'button white' do %>
	    			<span class="span">Home</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span>
					<% end %>
				</li>
				<li>
					<% if current_user.profile.present? %>
						<%= link_to users_path( user_id: current_user.id ), :class => 'button white' do %>
							<span class="span">Profile</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
						<% end %>
					<% else %>
						<%= link_to new_user_profile_path( user_id: current_user.id ), :class => 'button white' do %>
							<span class="span">Profile</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
						<% end %>
					<% end %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Customers <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-group"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><%= link_to "Add New Customer", new_customer_path %></li>
						<li><%= link_to "Manage Customers", customers_path %></li>
						<li><div class="divider"></div></li>
						<li><%= link_to "Add Customer Status", new_customers_status_path %></li>
						<li><%= link_to "Manage Statuses", customers_statuses_path %></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Vendors <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-shopping-basket"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><%= link_to "Add New Vendor", new_vendor_path %></li>
						<li><%= link_to "Manage Vendors", vendors_path %></li>
						<li><div class="divider"></div></li>
						<li><%= link_to "Add Vendor Status", new_vendors_status_path %></li>
						<li><%= link_to "Manage Statuses", vendors_statuses_path %></li>
						<li><div class="divider"></div></li>
						<li><%= link_to "Add Vendor Type", new_vendors_type_path %></li>
						<li><%= link_to "Manage Types", vendors_types_path %></li>
						<li><div class="divider"></div></li>
						<li><%= link_to "New Job Data Sheet", '#' %></li>
					</ul>
				</li>
				<li>
					<%= link_to reports_path, :class => 'button white' do %>
	    			<span class="span">Reports</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-bar-chart"></span>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/navigation/_top_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to home_path, class: "navbar-brand" do %>
			  <i class="fa fa-gears"></i>
			  D.U.K.E.
			<% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<% if current_user.profile %>
							<%= current_user.profile.first_name %>
						<% else %>
							Account
						<% end %>
						<span class="caret"></span>
					</a>
				  <ul class="dropdown-menu">
				    <li>
							<% if current_user.profile.present? %>
								<%= link_to edit_user_profile_path( user_id: current_user.id ), :class => 'button white' do %>
									<span id="span">Profile</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
								<% end %>
							<% else %>
								<%= link_to new_user_profile_path( user_id: current_user.id ), :class => 'button white' do %>
									<span id="span">Profile</span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
								<% end %>
							<% end %>
				    </li>
				    <li role="separator" class="divider"></li>
				    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
				  </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>